spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
#    jdbc:h2:file:./db/filmorate    |  jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true